-- =============================================================================
-- V1 __ baseline
--
-- 이 파일이 이 프로젝트 스키마의 출발점이다.
-- 지금까지는 ddl-auto=update 가 엔티티를 보고 테이블을 만들어 줬지만,
-- 이 시점부터 스키마의 주인은 Flyway 이고 Hibernate 는 검사(validate)만 한다.
--
-- 목표: 현재 엔티티 6개와 '정확히 일치하는' 스키마를 손으로 확정한다.
--       일치하지 않으면 ddl-auto=validate 가 기동을 실패시킨다. 그게 이 파일의 검증이다.
--
-- 작성 방법:
--   1) 현재 DB 구조를 뽑아 출발점으로 삼는다
--        pg_dump --schema-only --no-owner --no-privileges -d oauth2_idp > /tmp/current.sql
--   2) 아래 각 섹션에 해당 테이블 DDL 을 옮긴다
--   3) Hibernate 가 자동 생성한 이름을 사람이 읽을 수 있는 이름으로 바꾼다
--        예: uk_a1b2c3d4...  →  uq_credential_type_email
--   4) pg_dump 가 붙이는 잡음은 뺀다
--        SET / SELECT pg_catalog.set_config / OWNER TO / GRANT / COMMENT ON EXTENSION
--
-- 순서 규칙: 참조되는 테이블이 먼저. 아래 순서를 지키면 FK 오류가 안 난다.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. account  (사람)
--    참조하는 곳 없음 → 제일 먼저
--    엔티티: domain/Account.java
--

CREATE TABLE account (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_name text,
    phone_idx character varying(255),
    phone_number character varying(255),
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT account_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[]))),
    CONSTRAINT account_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'BLOCKED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------------------------------



-- -----------------------------------------------------------------------------
-- 2. credential  (로그인 수단, 단일테이블 STI)
--    account 를 참조 → account 다음
--    엔티티: domain/Credential.java
--

CREATE TABLE credential (
     id bigint NOT NULL,
     created_at timestamp(6) without time zone NOT NULL,
     email character varying(255),
     email_verified boolean NOT NULL,
     password_hash character varying(255),
     provider character varying(255),
     provider_uid character varying(255),
     type character varying(255),
     account_id bigint
);

--
-- Name: credential_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE credential ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME credential_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------------------------------



-- -----------------------------------------------------------------------------
-- 3. verification_challenge  (검증 챌린지)
--    account 를 참조
--    엔티티: domain/VerificationChallenge.java
--

CREATE TABLE verification_challenge (
    id bigint NOT NULL,
    attempt_count integer NOT NULL,
    channel character varying(255) NOT NULL,
    code_hash character varying(255) NOT NULL,
    consumed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    last_attempt_at timestamp(6) with time zone,
    purpose character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    account_id bigint NOT NULL,

    CONSTRAINT verification_challenge_channel_check CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'KAKAO_MSG'::character varying, 'SMS'::character varying])::text[]))),
    CONSTRAINT verification_challenge_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['SIGNUP_VERIFY'::character varying, 'LINK'::character varying])::text[]))),
    CONSTRAINT verification_challenge_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONSUMED'::character varying, 'SUPERSEDED'::character varying])::text[])))
);

--
-- Name: verification_challenge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE verification_challenge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME verification_challenge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------------------------------



-- -----------------------------------------------------------------------------
-- 4. refresh_token_family  (refresh 토큰 패밀리)
--    account_id 는 FK 가 아니라 그냥 bigint 다 (엔티티가 그렇게 돼 있다)
--    엔티티: domain/RefreshTokenFamily.java
--

CREATE TABLE refresh_token_family (
     id bigint NOT NULL,
     account_id bigint,
     client_id character varying(255),
     created_at timestamp(6) with time zone,
     status character varying(255),
     CONSTRAINT refresh_token_family_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'REVOKED'::character varying])::text[])))
);

--
-- Name: refresh_token_family_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE refresh_token_family ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_token_family_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------------------------------



-- -----------------------------------------------------------------------------
-- 5. refresh_token  (refresh 토큰 장부)
--    refresh_token_family 를 참조
--    엔티티: domain/RefreshToken.java
--

CREATE TABLE refresh_token (
    jti character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone,
    issued_at timestamp(6) with time zone,
    status character varying(255),
    version bigint NOT NULL,
    family_id bigint,
    CONSTRAINT refresh_token_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CONSUMED'::character varying, 'REVOKED'::character varying])::text[])))
);

-- -----------------------------------------------------------------------------



-- -----------------------------------------------------------------------------
-- 6. jpa_oauth2_authorization  (SAS 인가기록 — 우리 직접 구현)
--    FK 없음
--    엔티티: domain/JpaOAuth2Authorization.java
--

CREATE TABLE jpa_oauth2_authorization (
    id character varying(100) NOT NULL,
    access_token_expires_at timestamp(6) with time zone,
    access_token_issued_at timestamp(6) with time zone,
    access_token_metadata text,
    access_token_scopes character varying(1000),
    access_token_type character varying(100),
    access_token_value text,
    attributes text,
    authorization_code_expires_at timestamp(6) with time zone,
    authorization_code_issued_at timestamp(6) with time zone,
    authorization_code_metadata text,
    authorization_code_value text,
    authorization_grant_type character varying(100),
    authorized_scopes character varying(1000),
    oidc_id_token_expires_at timestamp(6) with time zone,
    oidc_id_token_issued_at timestamp(6) with time zone,
    oidc_id_token_metadata text,
    oidc_id_token_value text,
    principal_name character varying(200),
    refresh_token_expires_at timestamp(6) with time zone,
    refresh_token_issued_at timestamp(6) with time zone,
    refresh_token_metadata text,
    refresh_token_value text,
    registered_client_id character varying(100),
    state character varying(500)
);

-- -----------------------------------------------------------------------------

--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: credential credential_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credential
    ADD CONSTRAINT credential_pkey PRIMARY KEY (id);

--
-- Name: refresh_token_family refresh_token_family_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY refresh_token_family
    ADD CONSTRAINT refresh_token_family_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (jti);


--
-- Name: credential uq_credential_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credential
    ADD CONSTRAINT uq_credential_provider UNIQUE (provider, provider_uid);


--
-- Name: credential uq_credential_type_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credential
    ADD CONSTRAINT uq_credential_type_email UNIQUE (type, email);


--
-- Name: verification_challenge verification_challenge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY verification_challenge
    ADD CONSTRAINT verification_challenge_pkey PRIMARY KEY (id);



ALTER TABLE ONLY jpa_oauth2_authorization
    ADD CONSTRAINT jpa_oauth2_authorization_pkey PRIMARY KEY (id);
--
-- Name: idx_account_phone_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_phone_idx ON account USING btree (phone_idx);


--
-- Name: idx_credential_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_credential_account ON credential USING btree (account_id);


--
-- Name: idx_rt_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rt_expires ON refresh_token USING btree (expires_at);


--
-- Name: idx_rt_family; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rt_family ON refresh_token USING btree (family_id);


--
-- Name: idx_vc_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vc_expires ON verification_challenge USING btree (expires_at);


--
-- Name: idx_vc_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vc_lookup ON verification_challenge USING btree (account_id, channel, purpose, status);


--
-- Name: refresh_token fkc3hodxv5ut96mtqdu21q04w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT fk_refresh_token_familyid FOREIGN KEY (family_id) REFERENCES refresh_token_family(id);


--
-- Name: credential fkcgjhhuj1mkchkk8r00xhdqvo0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY credential
    ADD CONSTRAINT fk_credential_accountid FOREIGN KEY (account_id) REFERENCES account(id);


--
-- Name: verification_challenge fkix4xhwbpyga4021c2avidcvt4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY verification_challenge
    ADD CONSTRAINT fk_verification_challenge_accountid FOREIGN KEY (account_id) REFERENCES account(id);

